### ISSUE TITLE
seajs升级到2.3后 transport css的问题

### ISSUE THREAD

**Issue by deathfang** [spmjs/grunt-cmd-transport#86]
seajs升级到2.3后，没用seajs-style改用seajs-css (spm下装的1.02)，

``` javascript
define(function (require, exports, module){
    require('./c.css');
    var tpl = require('./c.tpl');
})
```

使用未构建的代码，可以请求到css,

构建时

``` javascript
module.exports = function (grunt) {
    var transport = require('grunt-cmd-transport');
    var style = transport.style.init(grunt);
    var template = transport.template.init(grunt);
    var script = transport.script.init(grunt);

transport : {
            options : {
                paths : ['.'],
                alias: '<%= pkg.spm.alias %>',
                parsers : {
                    '.js' : [script.jsParser],
                    '.css' : [style.cssParser],
                    '.tpl' : [template.tplParser]
                }
            },

```

得到的css成这样了

``` css
/*! define dist/component/show/c.css */
.m-imgText .gifAni { position: absolute; top: 50%; left: 50%;
    -webkit-transform: translate(-50%, -50%);
    -moz-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}
```

``` javascript
define("dist/component/show/show", [], function(require, exports, module) {
    require("./c.css");
})
```

最后结果就是没有请求 require的css

请教下 如何在模块内require css且构建正常使用
